### ISSUE TITLE
RFC: Solve Channel Muting 

### ISSUE THREAD

**Issue by JacobMGEvans** [kentcdodds/kcd-discord-bot-v1#1]
Idea is to create an automatic behavior of muting people (non-admin) when they enter the VOIP channels `kent-live` & `office-hours`

An alternative idea that sees when users are unmuted when first entering and DM's them with a friendly reminder.

**Comment by JacobMGEvans** [comment]
I might have found what we are looking for in the API 
If this value can be dynamically set on entry to the two Voice channels then this is exactly what can work. 
https://discord.js.org/#/docs/main/stable/class/VoiceState?scrollTo=selfMute

**Comment by JacobMGEvans** [comment]
So kind of the flow, I am thinking
1. Bot sleeps on those two voice channels -> 
2. Someone enters channel bot wakes up gets users ID-> 
3. VoiceState.selfMute is set to true (Kent can be exempted if we know his ID) -> 
4. Bot Sleeps -> 
5. New User Enters (Repeat) 

Since this only happens on channel entry they should be able to unmute.

**Comment by kentcdodds** [comment]
Unfortunately, I don't think that this value can be set for other people, only for the bot itself :-(

**Comment by JacobMGEvans** [comment]
**VoiceState API**
Represents the voice state for a Guild Member.

https://discord.js.org/#/docs/main/stable/class/VoiceState?scrollTo=setMute
Specifies that it is a Guild Member to be muted, not sure if this is moderation muting (so it needs to be tested)

**Comment by kentcdodds** [comment]
There's "self" and "server". With self it means that the user is only muted for the bot (not useful). With server it means the user is muted for everyone (what we want). Unfortunately when someone's been server muted they can't unmute themselves when they do want to talk so that's a bummer.

However, we could server mute them and message them to tell them a command they can run to unmute themselves I guess.

**Comment by JacobMGEvans** [comment]
> However, we could server mute them and message them to tell them a command they can run to unmute themselves I guess.

Yeah, that is definitely a good approach until something else can be figured out. Also, moderators can server unmute so, they can just message a mod that is on.

**Comment by kentcdodds** [comment]
I don't think we'll be able to make this work with the APIs available.
