### ISSUE TITLE
Hacktoberfest Label & RFC

### ISSUE THREAD

**Issue by JacobMGEvans** [kentcdodds/kcd-discord-bot-v1#10]
I think this can be an RFC for issues that can be labeled for Hacktoberfest
Easy to Intermediate. This doesn't need to be limited to the KCD bot however some good OSS 
intro issues for KCD members would be great! 

thoughts?

**Comment by kentcdodds** [comment]
I don't think this project is a good candidate for contributions because it's basically impossible to test whether changes worked. Will probably cause more work for me than I'm ready to commit to 🙈

**Comment by JacobMGEvans** [comment]
> I don't think this project is a good candidate for contributions because it's basically impossible to test whether changes worked. Will probably cause more work for me than I'm ready to commit to 🙈

What would be some suggestions in the KCD realm

**Comment by kentcdodds** [comment]
Honestly, I don't know how much time I'll have to help people during Hacktoberfest 😬

**Comment by kentcdodds** [comment]
We'll not be doing this in this repo. Sorry :-(
