### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/kcd-discord-bot-v1#11]
I want people to be able to give "kudos" to folks when they've been helpful in the community. I'm thinking this will be a command or an emoji reaction and when given the bot will post in a `#🥰-thanks` channel mentioning them and the message where they got kudos or something.

Maybe the person giving kudos should explain why they're getting kudos. So it could be:

```
?kudos @JacobMGEvans answered my question about how to deploy my react code and made me feel like a million bucks
```

Then that would be posted to the channel. This is precisely the type of gratitude I want to foster in the community. Any thoughts?

**Comment by sleepyArpan** [comment]
Great idea. Maybe adding specific roles to people when they reach certain kudo's points like `regular` or `helper` will encourage more people to participate in ongoing conversations.

**Comment by kentcdodds** [comment]
I think I may finally need to make a legit database to store this kind of info 😅

**Comment by balavishnuvj** [comment]
That's awesome, but how we plan to remind people to send "kudos"? Would be it more like a habit?

or can we remind the user to send kudos(using bot) when we encounter "thanks" or similar words?

**Comment by kentcdodds** [comment]
Good thought. Let's wait and see if that's needed 👍

**Comment by kentcdodds** [comment]
This is done. I may give "points" in the future or something, but for now we'll just stick with `?thanks` as a command. Maybe the bot could remind users when they see the word "thanks" or "thank you" in a message as @balavishnuvj suggested. That should be pretty easy.

**Comment by kentcdodds** [comment]
I just realized how annoying this could be... I feel like it'd be a good idea to come up with a way to disable this first...

Here's the code I wrote for this. Putting it here so I don't have to make a branch to keep it around.

```javascript
const {getChannel, getMessageLink} = require('./utils')

async function handleNewMessage(message) {
  if (message.author.bot) return
  if (!/thanks/i.test(message.content) && !/thank you/i.test(message.content)) {
    return
  }
  const {member} = message
  const link = getMessageLink(message)
  const botsChannel = getChannel(member.guild, {name: 'talk-to-bots'})
  await botsChannel.send(
    `
Hi ${member.user}! You sent someone a thank you in <${link}>. If you feel extra-grateful, you could send them a special thank you with the \`?thanks\` command.

Send me \`?thanks help\` for more details.
      `.trim(),
  )
}

module.exports = {handleNewMessage}
```

**Comment by balavishnuvj** [comment]
it could annoying, couple of things to keep in mind

- Frequeny at  which we remind(maybe we don't do for user above a level, signnifying more active users)
- Maybe a opt-out/opt-in role (We could add the role while on boarding, and in bots-only they can remove that role)

**Comment by smeijer** [comment]
Just dumping this thought I had, and mentioned in [`#general`](https://discordapp.com/channels/715220730605731931/715220730605731934/760888923982790677).

I've noticed the `#😍-thank-you` channel. And think it would be nice if there would be some kind of score board. Filter out `thanks @myself`, and render how many times users (top n) have been thanked.

It shows a kind of appreciation to active members that are trying to help others.

That way I could for example send the command `!helping-hands` in `#🤖-talk-to-bots `, and see a table with the top `n helpers`, with the number of how many times they were thanked.

```
jane     has been thanked 31 times
jack     has been thanked 30 times
...
```

**Comment by marcosvega91** [comment]
It's time for adding some storage 😆

**Comment by marcosvega91** [comment]
What do you think if we will save information on gist ?

**Comment by kentcdodds** [comment]
Thanks to @marcosvega91, we've got these thanks being preserved in a gist. Maybe one day when it's really large, it would be good to make a more real database, but for now this is super!

Thanks @marcosvega91!
