### ISSUE TITLE
Send someone a kif

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/kcd-discord-bot-v1#12]
Sometimes I want to send a kif to a specific person. So I'm thinking:

ACTUALLY NOT THIS:

```
@kentcdodds: ?kif hi @JacobMGEvans 
KCD Bot 🤖: To: @JacobMGEvans, from: @kentcdodds https://giphy.com/gifs/hi-kentcdodds-VbzmrabLQFE8VbQY3V
```

Yeah, that won't work very well because then they'd get two notifications for the message which wouldn't be cool. So I think all we'd need is the ability for `?kif` to ignore any mentions in the message.

So I think this would be sufficient:

```
@kentcdodds: ?kif hi @JacobMGEvans 
KCD Bot 🤖: https://giphy.com/gifs/hi-kentcdodds-VbzmrabLQFE8VbQY3V
```

So all we need to do in the command is to remove all mentions.

**Comment by JacobMGEvans** [comment]
well, how about this
```
@kentcdodds: ?kif hi @JacobMGEvans 
KCD Bot 🤖: To: JacobMGEvans From: Kent C Dodds https://giphy.com/gifs/hi-kentcdodds-VbzmrabLQFE8VbQY3V
```

If the @ is stripped out its still making the reference of To & From, and is searchable

**Comment by kentcdodds** [comment]
That makes sense to me @JacobMGEvans 👍 We could use `member.nickname` for that. This is relevant: https://discordjs.guide/miscellaneous/parsing-mention-arguments.html#how-discord-mentions-work

**Comment by kentcdodds** [comment]
This is done.
