### ISSUE TITLE
Ideas for custom commands

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/kcd-discord-bot-v1#2]
Anyone have ideas?

**Comment by JacobMGEvans** [comment]
Well besides ones related to finding your other content like Blogs umm... Maybe lists of content too like
!getVideosList
!getReposList
!getPodCasts

Oh speaking of podcasts what about something related to tieing in music/Spotify to Discord through the bot... That might be ultra-complex though.

**Comment by antoineneff** [comment]
Do you want to have a command to use your gifs ? Might be something like `?gif <keyword>` or `?react <keyword>`.

And then there's the clubs related commands but I don't know if you want to talk about it there or create a new issue for that.

**Comment by kentcdodds** [comment]
I'm thinking `?kcd-search <some query>` which will search across all my content and return the most relevant content (if someone wants to see all the results then they can go to https://kentcdodds.com/search which will use the same API... which will need to be built first).

As for music, we actually already support that with the `MEE6` bot.

We already have `/giphy` (which is built-into discord), so I think that we could have a `?kcd-gif <search>` command that will return one of [my reaction gifs](https://giphy.com/channel/kentcdodds). That would be kinda fun I think.

And then yeah, I'm going to work on the learning clubs automation today probably.

**Comment by JacobMGEvans** [comment]
> I'm thinking ?kcd-search <some query> which will search across all my content and return the most relevant content (if someone wants to see all the results then they can go to https://kentcdodds.com/search which will use the same API... which will need to be built first).

Interesting. A huge stretch goal for someone interested could be a simple Machine Learning that creates and updates a Dictionary of keywords mapped to related to the query. The metric could be based on if its really helpful or related the user can add a certain emoji if it wasn't helpful they can add different negative emoji.

**Comment by marcosvega91** [comment]
I'd like to learn something about discord bot, do you need an help doing something? Could I take a look at `kcd-gif` bot ? 🚀

**Comment by kentcdodds** [comment]
Sure!

**Comment by marcosvega91** [comment]
Could be useful to search on giphy using your channel like "@kentcdodds #yes" but it should be verified. I want to try if calling the API give the same problem

**Comment by marcosvega91** [comment]
it is giving the same error with the API

**Comment by kentcdodds** [comment]
I just submitted an application to be verified. We'll see 🤷‍♂️

**Comment by kentcdodds** [comment]
We're tracking custom commands in other issues :)
