### ISSUE TITLE
Figure out what the heck happened to the bot

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/kcd-discord-bot-v1#32]
The bot was doing really weird things. I had to revert to https://github.com/kentcdodds/kcd-discord-bot/commit/c868914fa711e4e4f4d01b69878ae9b2829d9339 in this commit: https://github.com/kentcdodds/kcd-discord-bot/commit/61a7fd26b9a18e963d2b9b92468a0a8bea725453 and everything went back to normal.

So something in there messed things up. It seemed like it was onboarding cleanup related. The bot would stop responding to the user's messages and then it started sending a message every 5 seconds or so saying that their channel was going to get deleted 😬

**Comment by kentcdodds** [comment]
Turns out it also kicked TONS of people 🤦‍♂️

**Comment by marcosvega91** [comment]
https://github.com/kentcdodds/kcd-discord-bot/blob/87991ef997e82ec522f5a87a05e7440ddb89e335/src/onboarding/utils.js#L43-L53

It should be `return !memberRoles.some(r => hasRole(member, r))`? 🤔

**Comment by kentcdodds** [comment]
Ok, I think I've fixed this. 🤞

Thanks @marcosvega91!

**Comment by kentcdodds** [comment]
I tried adding tests for `cleanup`: https://github.com/kentcdodds/kcd-discord-bot/tree/pr/add-tests-to-cleanup

I was having some issues with some logs about aborted requests and the client not having a token 🤔

**Comment by smeijer** [comment]
As I understand it's hard/impossible to test the bot properly, before it's going to production?

It might be an idea to add a rate-limit to destructive actions like this. This can be easy, or complex, depending on the needs.

- Simple rate limit, kick max `n users` every `n seconds`
- Check healthy average, and only rate limit when exceeding the 95th percentile
- Send a message to a (private) `bot-mgmt` channel mentioning the rate limit
- Add a `approve token` to the message above, allowing you to lift the rate limit for `n minutes` 
    `?firewall approve {:token} {:duration?}`

Just for those moments that you have nothing to do, and feel bored :grin:

**Comment by marcosvega91** [comment]
> I tried adding tests for `cleanup`: https://github.com/kentcdodds/kcd-discord-bot/tree/pr/add-tests-to-cleanup
> 
> I was having some issues with some logs about aborted requests and the client not having a token 🤔

The problem you are facing I think is something related to the `afterEach` cleanup. In the `afterEach` the discord client is destroyed. Destroying the client means remove the token, close WS connection (we are not using ) and clean some intervals.

I'm not sure that what you're waiting in the cleanup is right 

`mapValues` will return a new map object. To get all promises I think you should call `values()` function like 

```js
const promises = [
  ...channelDeletes.values(),
  ...homelessUnconfirmedMembersKicks.values(),
]
await Promise.all(promises)
```

**Comment by kentcdodds** [comment]
Thanks @marcosvega91! I've made several improvements to the project related to cleanup. For example, thanks to https://github.com/ealmansi/set-interval-async, we'll now wait for cleanup to *finish* before running cleanup again (in case cleanup takes more than 5000ms).

Gotta figure out tests for cleanup next.
