### ISSUE TITLE
Allow to move post when duplicate is detected

### ISSUE THREAD

**Issue by Aprillion** [kentcdodds/kcd-discord-bot-v1#35]
From conversation starting in https://discord.com/channels/715220730605731931/715225293471744021/772924289296629791

When the bot detects a user posting a duplicate message (e.g. because a moderator suggested that the message is better suited in some different room), it would be nice if the bot allowed the user to "Move the post to this channel" == delete the original post and allow it in the new channel.

**Comment by kentcdodds** [comment]
Right now, if someone tries to post the same thing in multiple channels the bot will let the user know and they have to manually delete the old message and post it in the correct channel. So is what you're suggesting that we automate the "delete the old message" part (I think that's all we could automate). I'm not sure how valuable that would be, but how do you propose that would work?

**Comment by sudokoi** [comment]
I suppose these set of exchanges can be done:
1. The bot notifies the user: "Similar post has been found <ins>here</ins>"
2. To delete the older message and keep the newer one, pls react with "some-unique-emoji" (or something similar).
3. After some timeout, maybe the bot can default back to the current behavior.

**Comment by kentcdodds** [comment]
Sounds pretty sensible to me! I'm in favor 👍

**Comment by kentcdodds** [comment]
Thinking about this more, maybe it would make more sense to just delete the older post. I think we can assume that they found a better place for their message and are trying to post it in the right place.

That's the simplest solution and I think makes the most sense.

**Comment by kentcdodds** [comment]
Actually, while I was working on this, I think it's safer to delete the brand new message. Older messages can have emoji reactions and replies. Deleting them would be confusing to everyone.

I think we're going to keep the existing behavior and I don't think it's worth enhancing the bot further for this. Thanks!

**Comment by smeijer** [comment]
Agree. Deleting the oldest post might also stimulate spam, instead of reducing it. Deleting the newest (the double) is the best thing to do in my opinion.
