### ISSUE TITLE
?🦆 and ?💩 bots

### ISSUE THREAD

**Issue by Aprillion** [kentcdodds/kcd-discord-bot-v1#38]
Ideas for new bot commands:
?🦆 (?rubber_ducky) => for rubber ducky debugging
* reply to the user with a picture of a rubber ducky and say a random message from a list, e.g.: 
```
["I'm listening", "uh huh", "Are you sure?"]
```

?💩 (?wtf) => for expressing negative feelings and swearing about code that didn't work
* delete the message
* tag the user in a `?kif kody loves you` message in the `#🧠-health` (or other dedicated) channel
* include some nice words from a list of nice messages, e.g.:
```
[`Hi ${sender}, I've noticed that you're a bit stressed lately. Here's a hug: `]
```

> FTR: from a discussion that started in https://discord.com/channels/715220730605731931/730475079703724064/781898280920940544

**Comment by JacobMGEvans** [comment]
> ?💩 (?wtf) => for expressing negative feelings and swearing about code that didn't work
> 
> * delete the message
> * tag the user in a `?kif kody loves you` message in the `#🧠-health` (or other dedicated) channel
> * include some nice words from a list of nice messages, e.g.:
> 
> ```
> [`Hi ${sender}, I've noticed that you're a bit stressed lately. Here's a hug: `]
> ```
I don't know about this one.

**Comment by Aprillion** [comment]
> I don't know about this one.

@JacobMGEvans I only posted it here, because Kent replied `Love it` in the chat ...

I was only half serious when I wrote the suggestion, but I might actually use it from time to time myself if it gets implemented - since I cannot complain in person on coffee breaks (mandatory home office) and video conferencing with colleagues is awkward for expressing unfiltered negative feelings and permanent chat messages are not good for swearing either... So I was thinking there must be better options than throwing my computer out of the window 😂

**Comment by JacobMGEvans** [comment]
> > I don't know about this one.
> 
> @JacobMGEvans I only posted it here, because Kent replied `Love it` in the chat ...
> 
> I was only half-serious when I wrote the suggestion, but I might actually use it from time to time myself if it gets implemented - since I cannot complain in person on coffee breaks (mandatory home office) and video conferencing with colleagues is awkward for expressing unfiltered negative feelings and permanent chat messages are not good for swearing either... So I was thinking there must be better options than throwing my computer out of the window 😂

Oh ok, I think I understand the context of command and why to use it, it makes more sense now and I can get on board with that.

**Comment by JacobMGEvans** [comment]
Is swearing not allowed on the server? I wasn't aware or just want to maintain positivity as much as possible.

**Comment by Aprillion** [comment]
> Is swearing not allowed on the server? I wasn't aware or just want to maintain positivity as much as possible.

Huh - it did not even occur to me that I could swear in the existing channels if I really wanted... Nah, it's such a nice place, public hate does not fit into this community (regardless of using swear words or safe-for-work words), we are not reddit ;)

"The Oasis for nice interactions on the internet." if anyone wants to quote me.

Still, people should be free to express negative emotions in a safe environment if it's possible to do so without hurting anyone..

**Comment by JacobMGEvans** [comment]
Yeah, I swear a lot, and I have personally chosen to limit how much I do it in KCD out of respect for Kent and the community. 
I still do it occasionally lol

**Comment by kentcdodds** [comment]
To be clear, I don't swear. I don't like the way it makes me feel when I hear it. It's normally associated with unkindness. All that said, there's nothing in our code of conduct that says you can't on our server. Nobody's going to be disciplined just for swearing on the server (they may be disciplined if what they're actually saying goes against the COC of course). :)

**Comment by rbusquet** [comment]
I don't think I like the rubber duck idea. The point of posting a piece of code or ask for help is to get more people involved, even if I also understand that thinking about the problem from a different perspective will also be beneficial. 

And again I don't need a bot to help me with my stress, the point of venting in a public space is to get real people to either engage or also actively listening. There's no point if the message is deleted if I'm not breaking COC. Just let me vent and be heard.

I like that most of the current commands are mostly to _enforce_ communication. You can send a `?blog` post to someone asking for help or say `?thankyou`, or send a gif to someone else

**Comment by kentcdodds** [comment]
Yeah, I don't think this one's going to be happening, and I'm trying to clean up the issues a bit so I'm going to close this one.

Thanks for the ideas and discussion though!
