### ISSUE TITLE
Improve ?thanks command

### ISSUE THREAD

**Issue by smeijer** [kentcdodds/kcd-discord-bot-v1#40]
I see the `?thanks` command quite often being used without a `for`. The bot responds that the message could not be parsed (_You have to use the word "for" when thanking someone. For example: ?thanks @​user for being so nice and answering my questions_), but I believe that this experience can be improved. 

I see two variants in which people fail:

1. Missing the word `for`.
    
    ```
   ?thanks @user you did something awesome
    ```
    
    I think this could just be accepted as a valid thank you without to much hassle? 

2. No message at all. 
    
    ```
    ?thanks @user
    ```
    
    I think this could still be treated as a valid "thank you". The bot could just fall back to a more neutral message. Something like "_you got thanked 🎉! @​someone appreciates you!_". Leaving out the quote.

**Comment by kentcdodds** [comment]
Agreed 👍
