### ISSUE TITLE
Self-destructing message stayed alive

### ISSUE THREAD

**Issue by Aprillion** [kentcdodds/kcd-discord-bot-v1#44]
- `kcd-discord-bot` version: ?
- `node` version: ?
- `npm` version: ?

Relevant code or config: ?

What you did: N/A

What happened:

Following message in #📈-react-performance contains text `This message will self-destruct in about 7 seconds` but it didn't self-destruct:
https://discord.com/channels/715220730605731931/759594714637926440/795653476389879829

![no self-destruct](https://user-images.githubusercontent.com/1087670/103578265-8bc76300-4ed6-11eb-9fcc-e53f5ae8d227.png)

Reproduction repository: N/A

Problem description: ?

Suggested solution: ?

**Comment by kentcdodds** [comment]
Thanks for opening this. No idea what's going on here, but that's definitely a bug.

**Comment by kentcdodds** [comment]
Just tried to reproduce this one and couldn't so I'll call this a fluke. Thanks!
