### ISSUE TITLE
Add Commands to README 

### ISSUE THREAD

**Issue by JacobMGEvans** [kentcdodds/kcd-discord-bot-v1#48]
- Utilize the CLI documentation pattern for listing Discord bots commands & variations

**Comment by kentcdodds** [comment]
Hmmm... I'm not sure why we'd need this because you can just type `?help` in discord. Not many people come to this repo to learn about the bot 🤷‍♂️

**Comment by JacobMGEvans** [comment]
Because I had straight forgotten ALL the commands and came here looking for them lol "Need" is a strong word, I just ended up asking someone else on the Discord lol
