### ISSUE TITLE
Expand streaming capabilities (a la clubhouse)

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/kcd-discord-bot-v1#49]
I think the clubhouse model is very interesting and I think we could get the bot to facilitate this sort of thing building on the existing streaming stuff.

Here are the new features I think we could have (using the command `?clubhouse` but thinking we could come up with a better name):

```
?clubhouse help

This is the list of the available commands:
- Send `?clubhouse start "Topic of conversation"` and I'll create a temporary voice channel and notify your followers. If you don't already have a "follow me" message, I'll post one for you in the `#🚨-follow-me` channel so people can sign up to be notified when you join a clubhouse.
- Send `?clubhouse schedule "Topic of conversation" for Wednesdays at 3:00 PM MDT` to schedule a recurring clubhouse. I'll also post in the `#🚨-upcoming-clubhouses` channel so people can opt-into getting notified when it starts.
- Send `?clubhouse schedule "Topic of conversation" for tomorrow at 2:31 PM MDT` to schedule a one-time clubhouse. I'll also post in the `#🚨-upcoming-clubhouses` channel so people can opt-into getting notified when it starts.
```

So we'd have a `follow-me` channel with messages like this:

```
React to this message with ✋ to be notified when @so-and-so starts/schedules a clubhouse meeting.
```

And the upcoming clubhouse messages would be just like the upcoming streams thing we have now.

I think that the streams could morph into this (or maybe we just keep calling them streams and we just add some of these features).

A key feature here is the ability to schedule these whenever and not worry about overlap because the voice channel will be created on-demand rather than reusing the same voice channel for everyone.

Thoughts?

Here's where we're at

- [x] Rename "stream" to "meetup"
- [x] Start a stream "now"
- [x] Create the follow-me channel and command
- [x] Notify all followers and opt-in-ers when a stream is ready to go
- [x] Create a new voice channel when the meetup begins
- [x] If the meetup title has a zoom link, don't create a voice channel
- [x] Add ability to delete follow-me messages
- [x] Add ability to schedule recurring meetups
- [x] Add ability to update the description for a scheduled meetup

**Comment by tigerabrodi** [comment]
Sounds great. :blue_heart: 

A question: The commands for recurring clubhouses and a one-time clubhouse seem to be the same or very similar? How do you plan on distinguishing them from each other? :thinking: 

An idea could be to keep the same flag, but for recurring ones perhaps add a flag of "-R" at the end or something like that. :sunglasses:

**Comment by smeijer** [comment]
I like the idea that you outline, but I don't see how it's different from the current streams.

Maybe we should just improve that? The temporary rooms/channels for active streams sound like a useful addition to prevent overlap.

If we'd add a `voice` or `video` option, then we basically have `clubhouse`? Right?

Feel free to rename `stream` to `clubhouse`. 😬

**Comment by Aprillion** [comment]
> Feel free to rename `stream` to `clubhouse`.

I am more happy with `stream` and I don't have a need for clubhouses TBH. Overlapping temporary voice channels sound confusing to me, but I will be happy to just not use the feature, not trying to discourage any experiments to improve streaming bot :)

**Comment by kentcdodds** [comment]
I'm worried that "Learning Clubs" and "Clubhouse" might be a confusing combination since they have nothing to do with each other... But I don't want to put this feature into a box. It's not just for streaming, chatting, podcasting, office-hours-ing, etc. It's for any and all of those things... Hmmm...

**Comment by kentcdodds** [comment]
How about "meetup"?

**Comment by kentcdodds** [comment]
Yeah, we're going with meetup :)

**Comment by kentcdodds** [comment]
Emoji is 🪢

I hope most people have that. If not, they'll have it as soon as they update their OS.

**Comment by kentcdodds** [comment]
Made some amazing progress on this!

- [x] Add ability to delete follow-me messages
- [ ] Add ability to schedule recurring meetups

Other than that, this thing is good! Excited about this :)

**Comment by smeijer** [comment]
I don't know what awesome emoji you're thinking about, but "as soon as they update their OS" might take a looooooong time for a lot of people. Discord also runs on phones. And a lot of phones run for many years, without a single update.

`meetup` sounds good to me. 

Screenshot taken on Android 10. 

![Screenshot_20210218-084238](https://user-images.githubusercontent.com/1196524/108322343-a70bda80-71c5-11eb-9862-f250f2438b87.jpg)

**Comment by Aprillion** [comment]
@smeijer the Unicode 13 character does not work on macOS Mojave or Windows 10 either, but I was able to copy&paste it for search => https://emojipedia.org/knot/

Discord client seems to support :knot: 
<img width="89" alt="Screenshot 2021-02-18 at 09 40 36" src="https://user-images.githubusercontent.com/1087670/108329444-7cbe1b00-71cd-11eb-9eb7-99c2b786bda8.png">

**Comment by kentcdodds** [comment]
Alright, I'm open to other suggestions 😅

Unfortunately discord emoji aren't rendered in channel names, otherwise we could make some sweet custom emoji for those 😔

**Comment by Aprillion** [comment]
what about one of these: 🗣  🏫  💡 🤔

**Comment by kentcdodds** [comment]
I like 💡 👍

**Comment by kentcdodds** [comment]
Alright! So meetups is basically feature complete. Only one smallish thing left and that's adding the ability to update the details of a scheduled meetup. I'm pretty sure we'll do something like:

```
?meetups update <link-to-meetup> "New subject" and other descriptive info
```

That shouldn't be an enormous challenge, and it's something that can be added even after people start using meetups so I feel comfortable encouraging people to start using this.

I'm going to migrate my office hours and "kent live" stuff over to this myself :)

**Comment by kentcdodds** [comment]
Alright, that's implemented now. We've got ourselves meetups!
