### ISSUE TITLE
Link for Changing Discord Avatar is Broken

### ISSUE THREAD

**Issue by jdsandifer** [kentcdodds/kcd-discord-bot-v1#75]
- `kcd-discord-bot` version: It's named kcd#2563. Is that the version? (It was accessed on 2021-07-12 at about 5:30a GMT.) 
- `node` version: don't know
- `npm` version: don't know

What you did: I was filling out the welcome questions with the bot.

What happened: At the avatar step, it listed a link to a Discord help article that didn't work.

Link address: https://support.discord.com/hc/en-us/articles/204156688-How-do-I-change-my-avatar-
![image](https://user-images.githubusercontent.com/11567955/125235674-af110780-e297-11eb-8851-e070044677fa.png)

Problem description: Seems like that link is broken.

Suggested solution: This seems to be the best current link (including the jump to the appropriate section): https://support.discord.com/hc/en-us/articles/360035491151-Account-Customization#h_3b115372-f09d-42cf-a02c-d7db97272735

**Comment by kentcdodds** [comment]
Thanks a bunch! 👏👏 Deploying a fix now 👍

**Comment by kentcdodds** [comment]
@all-contributors please add @jdsandifer for bugs
