### ISSUE TITLE
Google Form doesn't accept `hello i am a username#0001` as a valid discord username

### ISSUE THREAD

**Issue by jasikpark** [kentcdodds/kcd-discord-bot-v1#85]
- `kcd-discord-bot` version:
- `node` version:
- `npm` version:

Relevant code or config

```javascript
```

What you did: I tried to sign up for an epic react learning club with my discord username that has spaces in it

What happened: I got a "please submit a valid discord username" error, though my discord username is valid according to discord. 

<img width="818" alt="image" src="https://user-images.githubusercontent.com/10626596/157118698-add1ada0-277c-4b37-a861-66357040672f.png">

Reproduction repository:

Problem description:

Suggested solution: Please relax the restrictions around inputting a discord username; I think the length of the username input might be a little short as well? I tried putting in `hello[space]i[space]am[space]a[space]username#0001` and got the same error.

This isn't directly related to the bot of course, but I assume the google forms have a template somewhere?

**Comment by kentcdodds** [comment]
Fixed :) Thanks!
